//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NativeBlazorRvLocalizationWebAssembly.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ReportViewerMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReportViewerMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NativeBlazorRvLocalizationWebAssembly.Resources.ReportViewerMessages", typeof(ReportViewerMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click &apos;Refresh&apos; to restore client session..
        /// </summary>
        public static string ReportViewer_ClientExpired {
            get {
                return ResourceManager.GetString("ReportViewer_ClientExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating report document (Report = &apos;{0}&apos;; Format = &apos;{1}&apos;)..
        /// </summary>
        public static string ReportViewer_ErrorCreatingReportDocument {
            get {
                return ResourceManager.GetString("ReportViewer_ErrorCreatingReportDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error sending report document (Report = &apos;{0}&apos;)..
        /// </summary>
        public static string ReportViewer_ErrorSendingDocument {
            get {
                return ResourceManager.GetString("ReportViewer_ErrorSendingDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input a valid value..
        /// </summary>
        public static string ReportViewer_InvalidParameter {
            get {
                return ResourceManager.GetString("ReportViewer_InvalidParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done. Total {0} pages loaded..
        /// </summary>
        public static string ReportViewer_LoadedReportPagesComplete {
            get {
                return ResourceManager.GetString("ReportViewer_LoadedReportPagesComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading report....
        /// </summary>
        public static string ReportViewer_LoadingReport {
            get {
                return ResourceManager.GetString("ReportViewer_LoadingReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} pages loaded so far....
        /// </summary>
        public static string ReportViewer_LoadingReportPagesInProgress {
            get {
                return ResourceManager.GetString("ReportViewer_LoadingReportPagesInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing or invalid parameter value. Please input valid data for all parameters..
        /// </summary>
        public static string ReportViewer_MissingOrInvalidParameter {
            get {
                return ResourceManager.GetString("ReportViewer_MissingOrInvalidParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No page to display..
        /// </summary>
        public static string ReportViewer_NoPageToDisplay {
            get {
                return ResourceManager.GetString("ReportViewer_NoPageToDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No report..
        /// </summary>
        public static string ReportViewer_NoReport {
            get {
                return ResourceManager.GetString("ReportViewer_NoReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select all.
        /// </summary>
        public static string ReportViewer_ParameterEditorSelectAll {
            get {
                return ResourceManager.GetString("ReportViewer_ParameterEditorSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clear selection.
        /// </summary>
        public static string ReportViewer_ParameterEditorSelectNone {
            get {
                return ResourceManager.GetString("ReportViewer_ParameterEditorSelectNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string ReportViewer_ParametersAreaPreviewButton {
            get {
                return ResourceManager.GetString("ReportViewer_ParametersAreaPreviewButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing document to download. Please wait....
        /// </summary>
        public static string ReportViewer_PreparingDownload {
            get {
                return ResourceManager.GetString("ReportViewer_PreparingDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing document to print. Please wait....
        /// </summary>
        public static string ReportViewer_PreparingPrint {
            get {
                return ResourceManager.GetString("ReportViewer_PreparingPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error shown. Throwing promises chain stop error..
        /// </summary>
        public static string ReportViewer_PromisesChainStopError {
            get {
                return ResourceManager.GetString("ReportViewer_PromisesChainStopError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report processing was canceled..
        /// </summary>
        public static string ReportViewer_RenderingCancelled {
            get {
                return ResourceManager.GetString("ReportViewer_RenderingCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        public static string ReportViewer_SearchDialogCaptionText {
            get {
                return ResourceManager.GetString("ReportViewer_SearchDialogCaptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string ReportViewer_SearchDialogClearTitle {
            get {
                return ResourceManager.GetString("ReportViewer_SearchDialogClearTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match Case.
        /// </summary>
        public static string ReportViewer_SearchDialogMatchCaseTitle {
            get {
                return ResourceManager.GetString("ReportViewer_SearchDialogMatchCaseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match Whole Word.
        /// </summary>
        public static string ReportViewer_SearchDialogMatchWholeWordTitle {
            get {
                return ResourceManager.GetString("ReportViewer_SearchDialogMatchWholeWordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate Down.
        /// </summary>
        public static string ReportViewer_SearchDialogNavigateDownTitle {
            get {
                return ResourceManager.GetString("ReportViewer_SearchDialogNavigateDownTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate Up.
        /// </summary>
        public static string ReportViewer_SearchDialogNavigateUpTitle {
            get {
                return ResourceManager.GetString("ReportViewer_SearchDialogNavigateUpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results.
        /// </summary>
        public static string ReportViewer_SearchDialogNoResultsLabel {
            get {
                return ResourceManager.GetString("ReportViewer_SearchDialogNoResultsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page.
        /// </summary>
        public static string ReportViewer_SearchDialogPageText {
            get {
                return ResourceManager.GetString("ReportViewer_SearchDialogPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result {0} of {1}.
        /// </summary>
        public static string ReportViewer_SearchDialogResultsFormatLabel {
            get {
                return ResourceManager.GetString("ReportViewer_SearchDialogResultsFormatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing first {0} results..
        /// </summary>
        public static string ReportViewer_SearchDialogResultsLimitLabel {
            get {
                return ResourceManager.GetString("ReportViewer_SearchDialogResultsLimitLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to searching....
        /// </summary>
        public static string ReportViewer_SearchDialogSearchInProggress {
            get {
                return ResourceManager.GetString("ReportViewer_SearchDialogSearchInProggress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search in report contents.
        /// </summary>
        public static string ReportViewer_SearchDialogTitle {
            get {
                return ResourceManager.GetString("ReportViewer_SearchDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Regex.
        /// </summary>
        public static string ReportViewer_SearchDialogUseRegexTitle {
            get {
                return ResourceManager.GetString("ReportViewer_SearchDialogUseRegexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ReportViewer_SendEmailDialogCancelLabel {
            get {
                return ResourceManager.GetString("ReportViewer_SendEmailDialogCancelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CC:.
        /// </summary>
        public static string ReportViewer_SendEmailDialogCCLabel {
            get {
                return ResourceManager.GetString("ReportViewer_SendEmailDialogCCLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string ReportViewer_SendEmailDialogClose {
            get {
                return ResourceManager.GetString("ReportViewer_SendEmailDialogClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format:.
        /// </summary>
        public static string ReportViewer_SendEmailDialogFormatLabel {
            get {
                return ResourceManager.GetString("ReportViewer_SendEmailDialogFormatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From:.
        /// </summary>
        public static string ReportViewer_SendEmailDialogFromLabel {
            get {
                return ResourceManager.GetString("ReportViewer_SendEmailDialogFromLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string ReportViewer_SendEmailDialogSendLabel {
            get {
                return ResourceManager.GetString("ReportViewer_SendEmailDialogSendLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject:.
        /// </summary>
        public static string ReportViewer_SendEmailDialogSubjectLabel {
            get {
                return ResourceManager.GetString("ReportViewer_SendEmailDialogSubjectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Email.
        /// </summary>
        public static string ReportViewer_SendEmailDialogTitle {
            get {
                return ResourceManager.GetString("ReportViewer_SendEmailDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To:.
        /// </summary>
        public static string ReportViewer_SendEmailDialogToLabel {
            get {
                return ResourceManager.GetString("ReportViewer_SendEmailDialogToLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email format is not valid.
        /// </summary>
        public static string ReportViewer_SendEmailDialogValidationEmailFormat {
            get {
                return ResourceManager.GetString("ReportViewer_SendEmailDialogValidationEmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email format is not valid.
        /// </summary>
        public static string ReportViewer_SendEmailDialogValidationEmailFormat1 {
            get {
                return ResourceManager.GetString("ReportViewer_SendEmailDialogValidationEmailFormat1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email field is required.
        /// </summary>
        public static string ReportViewer_SendEmailDialogValidationEmailRequired {
            get {
                return ResourceManager.GetString("ReportViewer_SendEmailDialogValidationEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email field is required.
        /// </summary>
        public static string ReportViewer_SendEmailDialogValidationEmailRequired1 {
            get {
                return ResourceManager.GetString("ReportViewer_SendEmailDialogValidationEmailRequired1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format field is required.
        /// </summary>
        public static string ReportViewer_SendEmailDialogValidationFormatRequired {
            get {
                return ResourceManager.GetString("ReportViewer_SendEmailDialogValidationFormatRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format field is required.
        /// </summary>
        public static string ReportViewer_SendEmailDialogValidationFormatRequired1 {
            get {
                return ResourceManager.GetString("ReportViewer_SendEmailDialogValidationFormatRequired1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string ReportViewer_ToolbarExportTitle {
            get {
                return ResourceManager.GetString("ReportViewer_ToolbarExportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Page.
        /// </summary>
        public static string ReportViewer_ToolbarFirstPageTitle {
            get {
                return ResourceManager.GetString("ReportViewer_ToolbarFirstPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Page.
        /// </summary>
        public static string ReportViewer_ToolbarLastPageTitle {
            get {
                return ResourceManager.GetString("ReportViewer_ToolbarLastPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate Backward.
        /// </summary>
        public static string ReportViewer_ToolbarNavigateBackwardTitle {
            get {
                return ResourceManager.GetString("ReportViewer_ToolbarNavigateBackwardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate Forward.
        /// </summary>
        public static string ReportViewer_ToolbarNavigateForwardTitle {
            get {
                return ResourceManager.GetString("ReportViewer_ToolbarNavigateForwardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Page.
        /// </summary>
        public static string ReportViewer_ToolbarNextPageTitle {
            get {
                return ResourceManager.GetString("ReportViewer_ToolbarNextPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Page.
        /// </summary>
        public static string ReportViewer_ToolbarPreviousPageTitle {
            get {
                return ResourceManager.GetString("ReportViewer_ToolbarPreviousPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string ReportViewer_ToolbarPrintTitle {
            get {
                return ResourceManager.GetString("ReportViewer_ToolbarPrintTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string ReportViewer_ToolbarRefreshTitle {
            get {
                return ResourceManager.GetString("ReportViewer_ToolbarRefreshTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Search.
        /// </summary>
        public static string ReportViewer_ToolbarSearchTitle {
            get {
                return ResourceManager.GetString("ReportViewer_ToolbarSearchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send an email.
        /// </summary>
        public static string ReportViewer_ToolbarSendMailTitle {
            get {
                return ResourceManager.GetString("ReportViewer_ToolbarSendMailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Rendering.
        /// </summary>
        public static string ReportViewer_ToolbarStopRenderingTitle {
            get {
                return ResourceManager.GetString("ReportViewer_ToolbarStopRenderingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Document Map.
        /// </summary>
        public static string ReportViewer_ToolbarToggleDocumentMapTitle {
            get {
                return ResourceManager.GetString("ReportViewer_ToolbarToggleDocumentMapTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Parameters Area.
        /// </summary>
        public static string ReportViewer_ToolbarToggleParametersAreaTitle {
            get {
                return ResourceManager.GetString("ReportViewer_ToolbarToggleParametersAreaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Print Preview.
        /// </summary>
        public static string ReportViewer_ToolbarTogglePrintPreviewTitle {
            get {
                return ResourceManager.GetString("ReportViewer_ToolbarTogglePrintPreviewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle FullPage/PageWidth.
        /// </summary>
        public static string ReportViewer_ToolbarToggleScaleModeTitle {
            get {
                return ResourceManager.GetString("ReportViewer_ToolbarToggleScaleModeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom In.
        /// </summary>
        public static string ReportViewer_ToolbarZoomInTitle {
            get {
                return ResourceManager.GetString("ReportViewer_ToolbarZoomInTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom Out.
        /// </summary>
        public static string ReportViewer_ToolbarZoomOutTitle {
            get {
                return ResourceManager.GetString("ReportViewer_ToolbarZoomOutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get report parameters..
        /// </summary>
        public static string ReportViewer_UnableToGetReportParameters {
            get {
                return ResourceManager.GetString("ReportViewer_UnableToGetReportParameters", resourceCulture);
            }
        }
    }
}
