import Head from "next/head";
import { speakersData } from "../data/speakers";
import dynamic from 'next/dynamic'
import { process } from '@progress/kendo-data-query';
import { useState } from "react";
import '@progress/kendo-theme-default/dist/all.css';

const ViewerComponent = dynamic(() => import('../components/ViewerComponent'), {
  ssr: false,
})
const GridComponent = dynamic(() => import('../components/GridComponent'), {
  ssr: false,
})

export default function Home() {

  const [gridDataState, setGridDataState] = useState(() => ({
    data: process(speakersData, {
      sort: [
        { field: "Name", dir: "asc" }
      ],
    }),
    dataState: {
      sort: [
        { field: "Name", dir: "asc" }
      ],
    }
  })); 

  // Update the state based on the Grid component filter
 const handleDataStateChange = function (dataState) {
    setGridDataState({
      data: process(speakersData, dataState),
      dataState: dataState
    });
  }

    return (
      <>
      <Head>
          <title>Telerik Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div label="React Report Viewer">
          <div>
            <ViewerComponent data={gridDataState.data} dataState={gridDataState.dataState}></ViewerComponent>
          </div>
        </div>
        <div label="Kendo React Data Grid">
        <div>
          <GridComponent data={gridDataState.data} handleDataStateChange={handleDataStateChange} dataState={gridDataState.dataState}></GridComponent>
          </div>
        </div>
      </div>
    </>
    );
}
